version: 2.0
jobs:
  build:
    docker:
      - image: gulinux/planetaryimager_build:ubuntu-17.04-64bit
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          command: |
            export GTEST_OUTPUT=xml:/root/project/build/tests_result/
            mkdir -p build/tests_result
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_PLANETARYIMAGER_TESTING=On
            make -j4
            make test
            ls /root/project/build/tests_result/
      - store_test_results:
          path: /root/project/build/tests_result/
